#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 180

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "DqprZ/Wv4E34"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 8

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

